#!/bin/bash
# Guest/build-image.sh
# Builds the default Alpine Linux image for Lumina VMs.
# Works natively on macOS and Linux — no Docker, no sudo.
#
# Prerequisites: e2fsprogs (brew install e2fsprogs), curl, Go (for agent)
# Output: ~/.lumina/images/default/{vmlinuz, initrd, rootfs.img, lumina-agent, modules/}

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT_DIR="${1:-$HOME/.lumina/images/default}"
CUSTOM_KERNEL="${LUMINA_KERNEL:-}"  # Path to pre-built custom kernel (optional)
WORK_DIR=$(mktemp -d)
ALPINE_VERSION="3.20"
ALPINE_ARCH="aarch64"
ALPINE_MIRROR="https://dl-cdn.alpinelinux.org/alpine/v${ALPINE_VERSION}"
ROOTFS_SIZE_MB=1024

cleanup() { rm -rf "$WORK_DIR"; }
trap cleanup EXIT

BAKED_MODE=false
if [ -n "$CUSTOM_KERNEL" ] && [ -f "$CUSTOM_KERNEL" ]; then
    BAKED_MODE=true
fi

echo "=== Lumina Image Builder ==="
echo "Output: $OUTPUT_DIR"
if [ "$BAKED_MODE" = true ]; then
    echo "Mode:   BAKED (custom kernel, no initrd/modules)"
else
    echo "Mode:   LEGACY (Alpine kernel + initrd + modules)"
fi

# --- Prerequisites ---

AGENT_BINARY="$SCRIPT_DIR/lumina-agent/lumina-agent"
if [ ! -f "$AGENT_BINARY" ]; then
    echo "--- Building guest agent (Go cross-compile) ---"
    (cd "$SCRIPT_DIR/lumina-agent" && CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o lumina-agent .)
fi

# Find mke2fs — Homebrew installs e2fsprogs outside PATH on macOS
MKE2FS=$(command -v mke2fs 2>/dev/null || true)
if [ -z "$MKE2FS" ]; then
    for prefix in /opt/homebrew /usr/local; do
        if [ -x "$prefix/opt/e2fsprogs/sbin/mke2fs" ]; then
            MKE2FS="$prefix/opt/e2fsprogs/sbin/mke2fs"
            break
        fi
    done
fi
DEBUGFS=$(command -v debugfs 2>/dev/null || true)
if [ -z "$DEBUGFS" ]; then
    for prefix in /opt/homebrew /usr/local; do
        if [ -x "$prefix/opt/e2fsprogs/sbin/debugfs" ]; then
            DEBUGFS="$prefix/opt/e2fsprogs/sbin/debugfs"
            break
        fi
    done
fi
if [ -z "$MKE2FS" ] || [ -z "$DEBUGFS" ]; then
    echo "Error: e2fsprogs tools (mke2fs, debugfs) not found."
    if [[ "$(uname)" == "Darwin" ]]; then
        echo "  Install: brew install e2fsprogs"
    else
        echo "  Install: apt-get install e2fsprogs"
    fi
    exit 1
fi

# ============================================================
# Step 1: Download Alpine minirootfs
# ============================================================
echo "--- Step 1: Downloading Alpine minirootfs ---"
MINIROOTFS="alpine-minirootfs-${ALPINE_VERSION}.0-${ALPINE_ARCH}.tar.gz"
curl -fSL "${ALPINE_MIRROR}/releases/${ALPINE_ARCH}/${MINIROOTFS}" -o "$WORK_DIR/$MINIROOTFS"

# ============================================================
# Step 2: Obtain kernel (custom or Alpine virt)
# ============================================================
VMLINUZ=""
KMOD_DIR=""

if [ "$BAKED_MODE" = true ]; then
    echo "--- Step 2: Using custom kernel ---"
    VMLINUZ="$CUSTOM_KERNEL"
    echo "  vmlinuz:    $(du -h "$VMLINUZ" | cut -f1) (custom, CONFIG_MODULES=n)"
else
    echo "--- Step 2: Fetching Alpine virt kernel ---"

    # Get package version from APKINDEX
    curl -fsSL "${ALPINE_MIRROR}/main/${ALPINE_ARCH}/APKINDEX.tar.gz" \
        | tar xzf - -C "$WORK_DIR" APKINDEX 2>/dev/null
    PKGVER=$(awk '/^P:linux-virt$/,/^$/' "$WORK_DIR/APKINDEX" | awk -F: '/^V:/{print $2}')
    if [ -z "$PKGVER" ]; then
        echo "Error: could not determine linux-virt package version"
        exit 1
    fi
    echo "  linux-virt: $PKGVER"

    # APK files are gzip tarballs — extract directly, no chroot needed
    curl -fSL "${ALPINE_MIRROR}/main/${ALPINE_ARCH}/linux-virt-${PKGVER}.apk" \
        -o "$WORK_DIR/linux-virt.apk"
    mkdir -p "$WORK_DIR/kernel"
    tar xzf "$WORK_DIR/linux-virt.apk" -C "$WORK_DIR/kernel"

    VMLINUZ="$WORK_DIR/kernel/boot/vmlinuz-virt"
    KMOD_DIR=$(find "$WORK_DIR/kernel/lib/modules" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | head -1)

    if [ ! -f "$VMLINUZ" ]; then
        echo "Error: vmlinuz-virt not found in linux-virt package"
        echo "Contents of boot/:"
        ls -la "$WORK_DIR/kernel/boot/" 2>/dev/null || echo "(missing)"
        exit 1
    fi

    echo "  vmlinuz:    $(du -h "$VMLINUZ" | cut -f1)"
fi

# ============================================================
# Step 3: Create minimal initrd (legacy mode only)
# ============================================================
if [ "$BAKED_MODE" = true ]; then
    echo "--- Step 3: Skipping initrd (baked mode — kernel boots directly to rootfs) ---"
else
    # The stock Alpine initramfs is generated by mkinitfs during `apk add`,
    # which requires chroot. Instead, create a minimal initrd containing
    # only busybox — InitrdPatcher appends the custom init, agent, and
    # kernel modules at boot time.
    echo "--- Step 3: Creating minimal initrd ---"
    INITRD_DIR="$WORK_DIR/initrd-root"
    mkdir -p "$INITRD_DIR"/{bin,lib,proc,sys,dev,tmp,sysroot}
    # Busybox is dynamically linked against musl — include the dynamic linker
    tar xzf "$WORK_DIR/$MINIROOTFS" -C "$INITRD_DIR" ./bin/busybox ./lib/ld-musl-aarch64.so.1
    chmod 755 "$INITRD_DIR/bin/busybox"
    # ld-musl-aarch64.so.1 may be a symlink to libc.musl-*.so.1 — resolve it
    if [ -L "$INITRD_DIR/lib/ld-musl-aarch64.so.1" ]; then
        LIBC_TARGET=$(readlink "$INITRD_DIR/lib/ld-musl-aarch64.so.1")
        tar xzf "$WORK_DIR/$MINIROOTFS" -C "$INITRD_DIR" "./lib/$LIBC_TARGET"
    fi
    (cd "$INITRD_DIR" && ln -s busybox bin/sh)

    (cd "$INITRD_DIR" && find . | cpio -o -H newc 2>/dev/null) | gzip > "$WORK_DIR/initrd"
    echo "  initrd:     $(du -h "$WORK_DIR/initrd" | cut -f1)"
fi

# ============================================================
# Step 4: Build rootfs directory tree + ext4 image
# ============================================================
echo "--- Step 4: Building rootfs ---"
ROOTFS_DIR="$WORK_DIR/rootfs"
mkdir -p "$ROOTFS_DIR"
tar xzf "$WORK_DIR/$MINIROOTFS" -C "$ROOTFS_DIR"

# Install lumina-agent
mkdir -p "$ROOTFS_DIR/usr/local/bin"
cp "$AGENT_BINARY" "$ROOTFS_DIR/usr/local/bin/lumina-agent"
chmod 755 "$ROOTFS_DIR/usr/local/bin/lumina-agent"

# Full init script — works for both baked (direct boot) and legacy (InitrdPatcher override).
# For baked images: kernel boots directly to rootfs, runs this as PID 1.
# For legacy images: InitrdPatcher creates /sbin/lumina-init which switch_root calls instead.
#
# SYNC WARNING: Network config, virtiofs mount, and agent startup logic is shared with
# InitrdPatcher.customInitScript() in Sources/Lumina/InitrdPatcher.swift.
# If you change behavior here, check the legacy init script there too.
rm -f "$ROOTFS_DIR/sbin/init"
cat > "$ROOTFS_DIR/sbin/init" << 'INITEOF'
#!/bin/sh
# Lumina init — baked into rootfs image

mount -t proc proc /proc 2>/dev/null
mount -t sysfs sys /sys 2>/dev/null
mount -t devtmpfs dev /dev 2>/dev/null

# Boot profile markers — parsed by host from dmesg (BootProfile).
# Writes to /dev/kmsg; visible via SerialConsole or `dmesg | grep LUMINA_BOOT`.
_lumina_mark() { echo "LUMINA_BOOT phase=$1 t=$(cut -d' ' -f1 /proc/uptime)" > /dev/kmsg 2>/dev/null; }
_lumina_mark init_start

hostname lumina 2>/dev/null
ip link set lo up 2>/dev/null
ip link set eth0 up 2>/dev/null

# Parse all lumina_* kernel cmdline params in ONE pass.
LUMINA_MOUNTS=
LUMINA_ROSETTA=
LUMINA_NET_IP=
LUMINA_HOSTS=
for param in $(cat /proc/cmdline); do
  case "$param" in
    lumina_mounts=*)  LUMINA_MOUNTS="${param#lumina_mounts=}" ;;
    lumina_rosetta=*) LUMINA_ROSETTA="${param#lumina_rosetta=}" ;;
    lumina_ip=*)      LUMINA_NET_IP="${param#lumina_ip=}" ;;
    lumina_hosts=*)   LUMINA_HOSTS="${param#lumina_hosts=}" ;;
  esac
done

# Mount virtio-fs shares BEFORE agent starts (commands may need mounted paths)
if [ -n "$LUMINA_MOUNTS" ]; then
  OLD_IFS="$IFS"
  IFS=','
  for spec in $LUMINA_MOUNTS; do
    tag="${spec%%:*}"
    mpath="${spec#*:}"
    mkdir -p "$mpath"
    mount -t virtiofs "$tag" "$mpath" 2>/dev/null
  done
  IFS="$OLD_IFS"
fi

# Rosetta (x86_64 binary translation)
if [ "$LUMINA_ROSETTA" = "1" ]; then
  mkdir -p /mnt/rosetta
  mount -t virtiofs rosetta /mnt/rosetta 2>/dev/null
  if [ -f /mnt/rosetta/rosetta ]; then
    mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc 2>/dev/null
    echo ':rosetta:M::\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x3e\x00:\xff\xff\xff\xff\xff\xfe\xfe\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/mnt/rosetta/rosetta:F' > /proc/sys/fs/binfmt_misc/register 2>/dev/null
  fi
fi

# Background network config — off the critical path.
# The agent communicates via vsock (not TCP), so it can start and
# send 'ready' before the network is up.
(
  # Wait for carrier on eth0 (VZ NAT link takes ~100ms to come up)
  n=0
  while [ "$n" -lt 20 ] && ! ip link show eth0 2>/dev/null | grep -q 'state UP'; do
    sleep 0.1
    n=$((n+1))
  done

  # Disable IPv6 — VZ NAT only provides IPv4 routing.
  # The host-side `configure_network` (network.go) does this too;
  # keeping it here so eth0 stays sane even if the host driver
  # doesn't run (e.g. custom library callers that skip
  # `vm.configureNetwork()`).
  echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6 2>/dev/null

  # NOTE: udhcpc was previously invoked here as a fallback DHCP
  # client. Removed in v0.7.2 — the host driver always sends
  # `configure_network` over vsock (Lumina.run, Lumina.stream,
  # Lumina.createImage, SessionProcess, Pool, Network all call it),
  # which is faster and authoritative. udhcpc raced the host
  # driver, occasionally installed a different IP/route than the
  # host requested, and added 30–80 ms of churn on every boot.

  # Private networking config — LUMINA_NET_IP / LUMINA_HOSTS were parsed
  # from /proc/cmdline at init start (outer scope).
  if [ -n "$LUMINA_NET_IP" ]; then
    ip addr add "${LUMINA_NET_IP}/24" dev eth1 2>/dev/null
    ip link set eth1 up 2>/dev/null
  fi
  if [ -n "$LUMINA_HOSTS" ]; then
    echo "127.0.0.1 localhost" > /etc/hosts
    OLD_IFS="$IFS"
    IFS=','
    for entry in $LUMINA_HOSTS; do
      name="${entry%%:*}"
      addr="${entry#*:}"
      echo "$addr $name" >> /etc/hosts
    done
    IFS="$OLD_IFS"
  fi

  # Source network init if present (injected by InitrdPatcher for legacy images)
  if [ -f /lumina-net-init ]; then
    . /lumina-net-init
  fi
) &

_lumina_mark agent_exec
exec /usr/local/bin/lumina-agent
INITEOF
chmod 755 "$ROOTFS_DIR/sbin/init"

echo "--- Step 5: Creating rootfs.img (ext4, no mount/sudo) ---"
"$MKE2FS" -t ext4 -d "$ROOTFS_DIR" -b 4096 -q "$WORK_DIR/rootfs.img" "${ROOTFS_SIZE_MB}M"

# Fix file ownership — mke2fs -d copies host UIDs (e.g. 501 on macOS).
# Set all files/dirs to root:root so the rootfs has correct metadata.
UID_FIX="$WORK_DIR/fix_uids.cmds"
(cd "$ROOTFS_DIR" && find . -mindepth 1) | while IFS= read -r entry; do
    entry="${entry#./}"
    echo "set_inode_field \"$entry\" uid 0"
    echo "set_inode_field \"$entry\" gid 0"
done > "$UID_FIX"
"$DEBUGFS" -w -f "$UID_FIX" "$WORK_DIR/rootfs.img" >/dev/null 2>&1

# ============================================================
# Step 6: Copy outputs
# ============================================================
echo "--- Step 6: Saving to $OUTPUT_DIR ---"
mkdir -p "$OUTPUT_DIR"

# --- 6a: Copy kernel ---
if [ "$BAKED_MODE" = true ]; then
    # Custom kernel is already a raw ARM64 Image (built by build-kernel.sh)
    cp "$VMLINUZ" "$OUTPUT_DIR/vmlinuz"
    echo "  vmlinuz:    $(du -h "$OUTPUT_DIR/vmlinuz" | cut -f1) (custom)"
else
    # VZLinuxBootLoader on macOS requires an uncompressed kernel image.
    # Alpine's vmlinuz-virt is an EFI stub wrapping a gzip-compressed kernel.
    RAW_CHECK=$(dd if="$VMLINUZ" bs=1 skip=56 count=4 2>/dev/null | od -A n -t x1 | tr -cd '0-9a-f')
    if [ "$RAW_CHECK" = "41524d64" ]; then
        echo "  vmlinuz is already a raw ARM64 Image — copying as-is"
        cp "$VMLINUZ" "$OUTPUT_DIR/vmlinuz"
    else
        echo "  Decompressing vmlinuz to raw ARM64 Image..."
        GZIP_OFFSET=$(python3 -c "
import sys
data = open(sys.argv[1], 'rb').read()
idx = data.find(b'\x1f\x8b\x08')
print(idx if idx >= 0 else '')
" "$VMLINUZ")
        if [ -z "$GZIP_OFFSET" ]; then
            echo "  Warning: vmlinuz is neither raw ARM64 Image nor contains gzip stream"
            echo "  Copying as-is — VZLinuxBootLoader may reject this kernel"
            cp "$VMLINUZ" "$OUTPUT_DIR/vmlinuz"
        else
            tail -c +$((GZIP_OFFSET + 1)) "$VMLINUZ" | gunzip > "$OUTPUT_DIR/vmlinuz" 2>/dev/null || true
            VERIFY=$(dd if="$OUTPUT_DIR/vmlinuz" bs=1 skip=56 count=4 2>/dev/null | od -A n -t x1 | tr -cd '0-9a-f')
            if [ "$VERIFY" != "41524d64" ]; then
                echo "  Warning: Decompressed kernel missing ARM64 Image magic (got: $VERIFY)"
            fi
        fi
    fi
fi

# --- 6b: Copy rootfs ---
cp "$WORK_DIR/rootfs.img" "$OUTPUT_DIR/rootfs.img"

if [ "$BAKED_MODE" = true ]; then
    # Baked mode: only vmlinuz + rootfs.img — no initrd, modules, or separate agent
    echo "=== Done (baked image) ==="
    echo "Image saved to: $OUTPUT_DIR"
    echo "  vmlinuz:    $(du -h "$OUTPUT_DIR/vmlinuz" | cut -f1)"
    echo "  rootfs.img: $(du -h "$OUTPUT_DIR/rootfs.img" | cut -f1)"
    echo "  initrd:     (none — kernel boots directly to rootfs)"
    echo "  modules:    (none — compiled into kernel)"
    echo "  agent:      (baked into rootfs)"
else
    # Legacy mode: include initrd, modules, and separate agent binary
    # --- 6c: Copy initrd ---
    cp "$WORK_DIR/initrd" "$OUTPUT_DIR/initrd"

    # --- 6d: Copy guest agent binary ---
    cp "$AGENT_BINARY" "$OUTPUT_DIR/lumina-agent"
    chmod 755 "$OUTPUT_DIR/lumina-agent"

    # --- 6e: Extract kernel modules ---
    if [ -n "${KMOD_DIR:-}" ]; then
        mkdir -p "$OUTPUT_DIR/modules"
        find "$KMOD_DIR" \( \
            -name "virtio_blk.ko*" -o \
            -name "virtio_net.ko*" -o \
            -name "af_packet.ko" -o -name "af_packet.ko.*" -o \
            -name "failover.ko*" -o \
            -name "net_failover.ko*" -o \
            -name "ext4.ko*" -o \
            -name "jbd2.ko*" -o \
            -name "mbcache.ko*" -o \
            -name "crc16.ko*" -o \
            -name "crc32c_generic.ko*" -o \
            -name "libcrc32c.ko*" -o \
            -name "vsock.ko" -o -name "vsock.ko.*" -o \
            -name "vmw_vsock*.ko*" -o \
            -name "fuse.ko*" -o \
            -name "virtiofs.ko*" \
        \) -exec cp {} "$OUTPUT_DIR/modules/" \; 2>/dev/null
        MODULE_COUNT=$(ls "$OUTPUT_DIR/modules/" 2>/dev/null | wc -l | tr -d ' ')
        if [ "$MODULE_COUNT" -gt 0 ]; then
            echo "  modules:    $(ls "$OUTPUT_DIR/modules/" | tr '\n' ' ')"
        else
            echo "  Warning: No kernel modules found"
            rmdir "$OUTPUT_DIR/modules" 2>/dev/null
        fi
    else
        echo "  Warning: No kernel modules directory found"
    fi

    echo "=== Done (legacy image) ==="
    echo "Image saved to: $OUTPUT_DIR"
    echo "  vmlinuz:    $(du -h "$OUTPUT_DIR/vmlinuz" | cut -f1)"
    echo "  initrd:     $(du -h "$OUTPUT_DIR/initrd" | cut -f1)"
    echo "  rootfs.img: $(du -h "$OUTPUT_DIR/rootfs.img" | cut -f1)"
    [ -f "$OUTPUT_DIR/lumina-agent" ] && echo "  agent:      $(du -h "$OUTPUT_DIR/lumina-agent" | cut -f1)"
    [ -d "$OUTPUT_DIR/modules" ] && echo "  modules:    $(du -sh "$OUTPUT_DIR/modules/" | cut -f1)"
fi
