#!/bin/bash
# Guest/build-image.sh
# Builds the default Alpine Linux image for Lumina VMs.
# Works natively on macOS and Linux — no Docker, no sudo.
#
# Prerequisites: e2fsprogs (brew install e2fsprogs), curl, Go (for agent)
# Output: ~/.lumina/images/default/{vmlinuz, initrd, rootfs.img, lumina-agent, modules/}

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT_DIR="${1:-$HOME/.lumina/images/default}"
WORK_DIR=$(mktemp -d)
ALPINE_VERSION="3.20"
ALPINE_ARCH="aarch64"
ALPINE_MIRROR="https://dl-cdn.alpinelinux.org/alpine/v${ALPINE_VERSION}"
ROOTFS_SIZE_MB=1024

cleanup() { rm -rf "$WORK_DIR"; }
trap cleanup EXIT

echo "=== Lumina Image Builder ==="
echo "Output: $OUTPUT_DIR"

# --- Prerequisites ---

AGENT_BINARY="$SCRIPT_DIR/lumina-agent/lumina-agent"
if [ ! -f "$AGENT_BINARY" ]; then
    echo "--- Building guest agent (Go cross-compile) ---"
    (cd "$SCRIPT_DIR/lumina-agent" && GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o lumina-agent .)
fi

# Find mke2fs — Homebrew installs e2fsprogs outside PATH on macOS
MKE2FS=$(command -v mke2fs 2>/dev/null || true)
if [ -z "$MKE2FS" ]; then
    for prefix in /opt/homebrew /usr/local; do
        if [ -x "$prefix/opt/e2fsprogs/sbin/mke2fs" ]; then
            MKE2FS="$prefix/opt/e2fsprogs/sbin/mke2fs"
            break
        fi
    done
fi
if [ -z "$MKE2FS" ]; then
    echo "Error: mke2fs not found."
    if [[ "$(uname)" == "Darwin" ]]; then
        echo "  Install: brew install e2fsprogs"
    else
        echo "  Install: apt-get install e2fsprogs"
    fi
    exit 1
fi

# ============================================================
# Step 1: Download Alpine minirootfs
# ============================================================
echo "--- Step 1: Downloading Alpine minirootfs ---"
MINIROOTFS="alpine-minirootfs-${ALPINE_VERSION}.0-${ALPINE_ARCH}.tar.gz"
curl -fSL "${ALPINE_MIRROR}/releases/${ALPINE_ARCH}/${MINIROOTFS}" -o "$WORK_DIR/$MINIROOTFS"

# ============================================================
# Step 2: Download linux-virt APK, extract kernel + modules
# ============================================================
echo "--- Step 2: Fetching Alpine virt kernel ---"

# Get package version from APKINDEX
curl -fsSL "${ALPINE_MIRROR}/main/${ALPINE_ARCH}/APKINDEX.tar.gz" \
    | tar xzf - -C "$WORK_DIR" APKINDEX 2>/dev/null
PKGVER=$(awk '/^P:linux-virt$/,/^$/' "$WORK_DIR/APKINDEX" | awk -F: '/^V:/{print $2}')
if [ -z "$PKGVER" ]; then
    echo "Error: could not determine linux-virt package version"
    exit 1
fi
echo "  linux-virt: $PKGVER"

# APK files are gzip tarballs — extract directly, no chroot needed
curl -fSL "${ALPINE_MIRROR}/main/${ALPINE_ARCH}/linux-virt-${PKGVER}.apk" \
    -o "$WORK_DIR/linux-virt.apk"
mkdir -p "$WORK_DIR/kernel"
tar xzf "$WORK_DIR/linux-virt.apk" -C "$WORK_DIR/kernel"

VMLINUZ="$WORK_DIR/kernel/boot/vmlinuz-virt"
KMOD_DIR=$(find "$WORK_DIR/kernel/lib/modules" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | head -1)

if [ ! -f "$VMLINUZ" ]; then
    echo "Error: vmlinuz-virt not found in linux-virt package"
    echo "Contents of boot/:"
    ls -la "$WORK_DIR/kernel/boot/" 2>/dev/null || echo "(missing)"
    exit 1
fi

echo "  vmlinuz:    $(du -h "$VMLINUZ" | cut -f1)"

# ============================================================
# Step 3: Create minimal initrd (busybox only)
# ============================================================
# The stock Alpine initramfs is generated by mkinitfs during `apk add`,
# which requires chroot. Instead, create a minimal initrd containing
# only busybox — InitrdPatcher appends the custom init, agent, and
# kernel modules at boot time.
echo "--- Step 3: Creating minimal initrd ---"
INITRD_DIR="$WORK_DIR/initrd-root"
mkdir -p "$INITRD_DIR"/{bin,lib,proc,sys,dev,tmp,sysroot}
# Busybox is dynamically linked against musl — include the dynamic linker
tar xzf "$WORK_DIR/$MINIROOTFS" -C "$INITRD_DIR" bin/busybox lib/ld-musl-aarch64.so.1
chmod 755 "$INITRD_DIR/bin/busybox"
# ld-musl-aarch64.so.1 may be a symlink to libc.musl-*.so.1 — resolve it
if [ -L "$INITRD_DIR/lib/ld-musl-aarch64.so.1" ]; then
    LIBC_TARGET=$(readlink "$INITRD_DIR/lib/ld-musl-aarch64.so.1")
    tar xzf "$WORK_DIR/$MINIROOTFS" -C "$INITRD_DIR" "lib/$LIBC_TARGET"
fi
(cd "$INITRD_DIR" && ln -s busybox bin/sh)

(cd "$INITRD_DIR" && find . | cpio -o -H newc 2>/dev/null) | gzip > "$WORK_DIR/initrd"
echo "  initrd:     $(du -h "$WORK_DIR/initrd" | cut -f1)"

# ============================================================
# Step 4: Build rootfs directory tree + ext4 image
# ============================================================
echo "--- Step 4: Building rootfs ---"
ROOTFS_DIR="$WORK_DIR/rootfs"
mkdir -p "$ROOTFS_DIR"
tar xzf "$WORK_DIR/$MINIROOTFS" -C "$ROOTFS_DIR"

# Install lumina-agent
mkdir -p "$ROOTFS_DIR/usr/local/bin"
cp "$AGENT_BINARY" "$ROOTFS_DIR/usr/local/bin/lumina-agent"
chmod 755 "$ROOTFS_DIR/usr/local/bin/lumina-agent"

# Minimal init script (fallback — InitrdPatcher's lumina-init overrides this)
rm -f "$ROOTFS_DIR/sbin/init"
cat > "$ROOTFS_DIR/sbin/init" << 'INITEOF'
#!/bin/sh
mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t devtmpfs dev /dev
hostname lumina
ip link set lo up 2>/dev/null
ip link set eth0 up 2>/dev/null
udhcpc -i eth0 -s /usr/share/udhcpc/default.script -q 2>/dev/null &
exec /usr/local/bin/lumina-agent
INITEOF
chmod 755 "$ROOTFS_DIR/sbin/init"

echo "--- Step 5: Creating rootfs.img (ext4, no mount/sudo) ---"
"$MKE2FS" -t ext4 -d "$ROOTFS_DIR" -b 4096 -q "$WORK_DIR/rootfs.img" "${ROOTFS_SIZE_MB}M"

# ============================================================
# Step 6: Copy outputs
# ============================================================
echo "--- Step 6: Saving to $OUTPUT_DIR ---"
mkdir -p "$OUTPUT_DIR"

# --- 6a: Decompress vmlinuz to raw ARM64 Image ---
# VZLinuxBootLoader on macOS requires an uncompressed kernel image.
# Alpine's vmlinuz-virt is an EFI stub wrapping a gzip-compressed kernel.
RAW_CHECK=$(dd if="$VMLINUZ" bs=1 skip=56 count=4 2>/dev/null | od -A n -t x1 | tr -cd '0-9a-f')
if [ "$RAW_CHECK" = "41524d64" ]; then
    echo "  vmlinuz is already a raw ARM64 Image — copying as-is"
    cp "$VMLINUZ" "$OUTPUT_DIR/vmlinuz"
else
    echo "  Decompressing vmlinuz to raw ARM64 Image..."
    GZIP_OFFSET=$(python3 -c "
import sys
data = open(sys.argv[1], 'rb').read()
idx = data.find(b'\x1f\x8b\x08')
print(idx if idx >= 0 else '')
" "$VMLINUZ")
    if [ -z "$GZIP_OFFSET" ]; then
        echo "  Warning: vmlinuz is neither raw ARM64 Image nor contains gzip stream"
        echo "  Copying as-is — VZLinuxBootLoader may reject this kernel"
        cp "$VMLINUZ" "$OUTPUT_DIR/vmlinuz"
    else
        tail -c +$((GZIP_OFFSET + 1)) "$VMLINUZ" | gunzip > "$OUTPUT_DIR/vmlinuz" 2>/dev/null || true
        VERIFY=$(dd if="$OUTPUT_DIR/vmlinuz" bs=1 skip=56 count=4 2>/dev/null | od -A n -t x1 | tr -cd '0-9a-f')
        if [ "$VERIFY" != "41524d64" ]; then
            echo "  Warning: Decompressed kernel missing ARM64 Image magic (got: $VERIFY)"
        fi
    fi
fi

# --- 6b: Copy initrd ---
cp "$WORK_DIR/initrd" "$OUTPUT_DIR/initrd"

# --- 6c: Copy rootfs ---
cp "$WORK_DIR/rootfs.img" "$OUTPUT_DIR/rootfs.img"

# --- 6d: Copy guest agent binary ---
cp "$AGENT_BINARY" "$OUTPUT_DIR/lumina-agent"
chmod 755 "$OUTPUT_DIR/lumina-agent"

# --- 6e: Extract kernel modules ---
# Boot modules: virtio_blk, virtio_net, ext4 + deps (all =m in virt kernel)
# Agent modules: vsock chain
# Mount modules: fuse + virtiofs
if [ -n "${KMOD_DIR:-}" ]; then
    mkdir -p "$OUTPUT_DIR/modules"
    find "$KMOD_DIR" \( \
        -name "virtio_blk.ko*" -o \
        -name "virtio_net.ko*" -o \
        -name "net_failover.ko*" -o \
        -name "ext4.ko*" -o \
        -name "jbd2.ko*" -o \
        -name "mbcache.ko*" -o \
        -name "crc16.ko*" -o \
        -name "crc32c_generic.ko*" -o \
        -name "libcrc32c.ko*" -o \
        -name "vsock.ko" -o -name "vsock.ko.*" -o \
        -name "vmw_vsock*.ko*" -o \
        -name "fuse.ko*" -o \
        -name "virtiofs.ko*" \
    \) -exec cp {} "$OUTPUT_DIR/modules/" \; 2>/dev/null
    MODULE_COUNT=$(ls "$OUTPUT_DIR/modules/" 2>/dev/null | wc -l | tr -d ' ')
    if [ "$MODULE_COUNT" -gt 0 ]; then
        echo "  modules:    $(ls "$OUTPUT_DIR/modules/" | tr '\n' ' ')"
    else
        echo "  Warning: No kernel modules found"
        rmdir "$OUTPUT_DIR/modules" 2>/dev/null
    fi
else
    echo "  Warning: No kernel modules directory found"
fi

echo "=== Done ==="
echo "Image saved to: $OUTPUT_DIR"
echo "  vmlinuz:    $(du -h "$OUTPUT_DIR/vmlinuz" | cut -f1)"
echo "  initrd:     $(du -h "$OUTPUT_DIR/initrd" | cut -f1)"
echo "  rootfs.img: $(du -h "$OUTPUT_DIR/rootfs.img" | cut -f1)"
[ -f "$OUTPUT_DIR/lumina-agent" ] && echo "  agent:      $(du -h "$OUTPUT_DIR/lumina-agent" | cut -f1)"
[ -d "$OUTPUT_DIR/modules" ] && echo "  modules:    $(du -sh "$OUTPUT_DIR/modules/" | cut -f1)"
